fixing typo that caused a NameError (undefined local variable or method `geometry\' for #<Page:...>)
Signed-off-by: Tom Cowell <tc@eightsquarestudio.com>

Signed-off-by: Andrea Franz <andrea@gravityblast.com>